In [1]:
import pandas as pd
import numpy as np

In [34]:
# pd.read_excel(엑셀파일명,시트명,index_col=칼럼명)
df = pd.read_excel('09.2 KOSPI200 F 201712.xlsx',sheet_name = 'Sheet1',index_col= '일자')
df.index = pd.to_datetime(df.index)
df

              선물가격      지수
일자
2017-09-01  308.40  307.78
2017-09-04  305.60  304.19
2017-09-05  304.85  304.06
2017-09-06  304.30  303.18
2017-09-07  308.10  306.97
2017-09-08  308.35  307.43
2017-09-11  311.50  309.83
2017-09-12  311.45  310.42
2017-09-13  310.85  310.00
2017-09-14  313.60  312.52
2017-09-15  314.55  313.69
2017-09-18  320.05  318.93
2017-09-19  319.40  318.51
2017-09-20  319.15  318.48
2017-09-21  319.40  318.25
2017-09-22  317.10  316.71
2017-09-25  317.15  316.40
2017-09-26  315.15  314.29
2017-09-27  314.75  313.82
2017-09-28  314.95  313.85
2017-09-29  317.65  316.27
2017-10-10  323.50  322.49
2017-10-11  326.60  326.12
2017-10-12  329.00  328.11
2017-10-13  328.65  327.35
2017-10-16  328.85  327.82
2017-10-17  329.15  328.51
2017-10-18  329.20  328.40
2017-10-19  327.45  326.47
2017-10-20  329.60  328.89
...            ...     ...
2017-11-03  339.70  338.83
2017-11-06  337.50  337.40
2017-11-07  337.10  336.76
2017-11-08  338.60  337.80
2017-11-09  337.00  337.14
2017-11-10  336.25  335.96
2017-11-13  334.90  334.33
2017-11-14  334.65  333.62
2017-11-15  332.50  332.17
2017-11-16  334.65  334.36
2017-11-17  334.30  334.18
2017-11-20  332.80  332.92
2017-11-21  334.20  333.51
2017-11-22  335.90  335.49
2017-11-23  334.80  334.51
2017-11-24  335.60  335.44
2017-11-27  329.25  329.53
2017-11-28  331.05  330.99
2017-11-29  331.05  330.68
2017-11-30  325.60  325.25
2017-12-01  325.20  324.78
2017-12-04  328.35  328.77
2017-12-05  329.95  329.61
2017-12-06  325.00  324.52
2017-12-07  324.05  323.59
2017-12-08  324.75  324.68
2017-12-11  324.85  325.09
2017-12-12  323.80  324.07
2017-12-13  326.20  326.18
2017-12-14  327.65  324.74

[69 rows x 2 columns]

In [52]:
def futures_price(S,r,d,T,t0): # 함수선언 입력값으로 (기초자산 가격, 이자율, 배당률, 최종거래일, 기준일 )
    t = np.busday_count(t0,T) / 252
    print(t)
    F = S*np.exp((r-d)*t) # F= Se^((r-d)t)
    return F # 선물 이론가 반환

In [53]:
T = pd.to_datetime('2017-12-14') # 최종거래일
r = 0.0225 #이자율
d = 0.015 # 배당률
for n in (df.index) :
    t0 = n
    S = df.loc[n,'지수']
    F = futures_price (S ,r ,d, T, t0)
    f = '{:,.2f}'.format(F) # 이론가 숫자 포매팅
    df.loc[n,'이론가'] = f

TypeError: Iterator operand 0 dtype could not be cast from dtype('<M8[us]') to dtype('<M8[D]') according to the rule 'safe'

In [39]:
F = futures_price (S ,r ,d, '2017-12-14', '2017-01-01')
F

310.0601138783746